#!/usr/bin/env python3
#Dockerfile.python
#
# Copyright 2017 José Lopes de Oliveira Jr.
#
# Use of this source code is governed by a MIT-like
# license that can be found in the LICENSE file.
##


FROM python:3-onbuild
RUN apt update && apt upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt install -y git vim tshark
RUN git clone https://github.com/forkd/tesla
