#!/usr/bin/env python3
#Dockerfile.postgres
#
# Copyright 2017 José Lopes de Oliveira Jr.
#
# Use of this source code is governed by a MIT-like
# license that can be found in the LICENSE file.
##


FROM postgres
RUN apt update && apt upgrade -y
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD foobar
ENV POSTGRES_DB tesla
